### ISSUE TITLE
get_meter_id() currently bugged, does not return correct value

### ISSUE THREAD

**Issue by Tobias-Frei** [jpbede/pydiscovergy#2]
Hey,

get_meter_id() returns a String like "EASYMETER_12345678", which is not the correct meterID for the http-request. http-request requires a cryptic hex-code. 

In my case, i got it via using the 0.0.4-version of pydiscovergy get_meter_id().

**Comment by jpbede** [comment]
Will have a look into this tomorrow. Seems that they have changed their api.

**Comment by jpbede** [comment]
Fixed with version 1.1.0
