### ISSUE TITLE
New release - pytz pin incompatibility?

### ISSUE THREAD

**Issue by cdce8p** [jpbede/pydiscovergy#266]
The last release still pins `pytz = "^2023.3"` which prevents the update to `2024.01`. This was fixed in #227.
Would it be possible to do a new release soon?

/CC @jpbede

https://github.com/stub42/pytz/blob/master/tz/NEWS

**Comment by jpbede** [comment]
Yea sure, will do that later

**Comment by jpbede** [comment]
Published, will create a PR for Home Assistant now.
