### ISSUE TITLE
Allow install on Python 3.12

### ISSUE THREAD

**Issue by cdce8p** [jpbede/pydiscovergy#78]
The package requirements don't allow installs on `3.12` currently. That prohibits testing for applications that depend on this package, like Home Assistant. In general, it's better for libraries to keep their dependencies as open as possible for downstream apps to be able to resolve dependency conflicts. I would recommend `>=3.9` here.

https://github.com/jpbede/pydiscovergy/blob/60212da7313b78b66ed4738ce0f366cbb9de6bb7/pyproject.toml#L19

--
As a side note, since I saw the [discussion](https://github.com/home-assistant/core/pull/97186#issuecomment-1649561164) about the `authlib` pin, if the library is compatible with both `<1.0` and `>=1.0`, it's usually better to use something like `>=0.15`. Once all other dependency are ready to upgrade and open up their respective pins, the `authlib` update will happen automatically.

https://github.com/jpbede/pydiscovergy/blob/60212da7313b78b66ed4738ce0f366cbb9de6bb7/pyproject.toml#L20

**Comment by cdce8p** [comment]
Opened #79 to update the `authlib` requirement.

For Python, `dataclasses-json` needs to be updated first. Opened https://github.com/lidatong/dataclasses-json/pull/449 for that. Once a new version is released, it can open a PR here to update it as well.

**Comment by jpbede** [comment]
Thanks a lot. I've merged the `authlib` requirement. I'm now waiting for `dataclasses-json` before I create a new release.
